<?php

use WebChemistry\ErrorPresenter\ErrorHelper;

$config = ErrorHelper::getConfig();

$data = $config['messages'][$code] ?? $config['messages'][null] ?? [];
$home = $config['home'] ?? null;
$layout = $config['layout'] ?? __DIR__ . '/layout.phtml';
$homepage = ErrorHelper::getHomepage();
$primary = $config['colors']['primary'];
$secondary = $config['colors']['secondary'];

require_once $layout;
