<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title><?php echo $code; ?> <?php echo htmlspecialchars($data['title']); ?></title>

	<link rel="icon" type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACGElEQVQ4T32Tz2sTURDHvzO7sk2x/qhoFW1ibOPV1lOrIhgvevJQixA2lwpR6EXwHxHE2haUUEMvIeBRDy0iaHpQWjzZ2rQmRTFKKCWSZGv2PXlvm5ismjm9me/MZ2b2vSX4LGvb5yVwh4SICiCkZebPBrDoCjF9cX5+pbWEGs67RKK7Xq0+lFJO+KGtvgRm4Tj3LqTTVRXXAFXsVCovGbjUqbihEfBaOM41BdGApXj8ib8zMeHMWAgSwGYmDynU6Y8RMDOSSt0ltTOA9/7OvcO9OBU9ocNbC1+xvbL913BCiGF6a9szBCRaVTNg4OztCLZ2vK79BwirT9fhVuttEAE8pmws9gnMg61K39Xj6Bs6gky2osNjo90oLpdQXPzmX2OV3sRiu8y8r6F0He1CJD4AIrQBpATWnuXg/Kg1IQLYbQcQIXQziIPB/Tpp83tdX9PpY6b2d/I/kc8UAEUD4AFse42BiAr0DPYgfCPY7LBR/AUiQngPoKHPCyjnyl4O0Udasu1p9fLUzJGJAQQOWU2AfwIlVEo1rCdzOkdK+UitMMTMywrQfyuIwye98f9npUIZX9IFbwDmc/ohNa6y4rrYdd2OAMswEDAMlTM1mkpNeoDx8QBb1gsJXO5YvSdK4JVjmtevJJO15s+kILCsB/5H9Q/gVM0076tivYY/QX0TMCcMIOoCYaUz0YYUYoENY3Zkbu5Da81vy0LHK9paYv0AAAAASUVORK5CYII=" sizes="16x16">

	<style>
		h1, h3, p, .btn {
			font-family: Roboto,-apple-system,system-ui,BlinkMacSystemFont,Segoe UI,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,Arial,sans-serif;
			letter-spacing: .5px;
		}
		h1 {
			color: #f44336;
			font-size: 60px;
			margin-top: 0;
			margin-bottom: 20px;
		}
		h3 {
			color: #313435;
			font-weight: 500;
			font-size: 1.4rem;
			text-transform: capitalize;
			margin-bottom: 10px;
		}
		p {
			color: #72777a;
			margin-bottom: 40px;
		}
		.btn {
			color: #fff;
			background-color: #2196f3;
			display: inline-block;
			font-weight: 400;
			text-align: center;
			white-space: nowrap;
			vertical-align: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			-ms-user-select: none;
			user-select: none;
			border: 1px solid #2196f3;
			padding: .375rem .75rem;
			font-size: .875rem;
			line-height: 1.5;
			border-radius: .25rem;
			-webkit-transition: background-color .15s ease-in-out,border-color .15s ease-in-out,-webkit-box-shadow .15s ease-in-out;
			transition: background-color .15s ease-in-out,border-color .15s ease-in-out,-webkit-box-shadow .15s ease-in-out;
			-o-transition: background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
			transition: background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
			transition: background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out,-webkit-box-shadow .15s ease-in-out;
			text-decoration: none;
		}
		.btn:hover {
			color: #fff;
			background-color: #0c83e2;
			border-color: #0c7cd5;
		}
		.btn:focus {
			-webkit-box-shadow: 0 0 0 0.2rem rgba(33,150,243,.5);
			box-shadow: 0 0 0 0.2rem rgba(33,150,243,.5);
		}
		.flex, #content {
			display: flex;
			align-items: center;
			justify-content: center;
		}
		.right {
			margin-left: 40px;
		}
		#content, body, html {
			height: 100%;
		}
		@media (max-width: 550px) {
			.left {
				display: none;
			}
			.right {
				text-align: center;
			}
		}
	</style>
</head>
<body>
<div id="content">
	<div class="flex">
		<div class="left">
			<img src="data:image/png;base64,<?php echo base64_encode(file_get_contents($data['image'])); ?>" alt="<?php echo htmlspecialchars($data['title']); ?>">
		</div>
		<div class="right">
			<h1><?php echo $code; ?></h1>
			<h3><?php echo htmlspecialchars($data['title']); ?></h3>
			<p><?php echo htmlspecialchars($data['desc']); ?></p>
			<div>
				<a href="<?php echo $homepage; ?>" class="btn"><?php echo htmlspecialchars($home); ?></a>
			</div>
		</div>
	</div>
</div>
</body>
</html>
