<style>
	* {
		-webkit-box-sizing: border-box;
		box-sizing: border-box;
	}

	body {
		padding: 0;
		margin: 0;
	}

	#notfound {
		all: initial;
		position: fixed;
		user-select: none;
		background: #fff;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		display: flex;
		align-items: center;
		justify-content: center;
		z-index: 1000;
	}

	#notfound .notfound {
		all: initial;
		max-width: 767px;
		width: 100%;
		line-height: 1.4;
		text-align: center;
		padding: 15px;
	}

	.notfound .notfound-404 {
		position: relative;
		height: 220px;
	}

	.notfound .notfound-404 h1 {
		font-family: 'Kanit', sans-serif;
		position: absolute;
		left: 50%;
		top: 50%;
		-webkit-transform: translate(-50%, -50%);
		-ms-transform: translate(-50%, -50%);
		transform: translate(-50%, -50%);
		font-size: 186px;
		font-weight: 200;
		margin: 0px;
		background: linear-gradient(130deg, <?= $secondary ?>, <?= $primary ?>);
		color: transparent;
		-webkit-background-clip: text;
		background-clip: text;
		text-transform: uppercase;
	}

	.notfound h2 {
		font-family: 'Kanit', sans-serif;
		font-size: 33px;
		font-weight: 200;
		text-transform: uppercase;
		margin-top: 0px;
		margin-bottom: 25px;
		letter-spacing: 3px;
	}


	.notfound p {
		font-family: 'Kanit', sans-serif;
		font-size: 16px;
		font-weight: 200;
		margin-top: 0px;
		margin-bottom: 25px;
	}


	.notfound a {
		font-family: 'Kanit', sans-serif;
		color: <?= $primary ?>;
		font-weight: 200;
		text-decoration: none;
		border-bottom: 1px dashed<?= $primary ?>;
		border-radius: 2px;
	}

	.notfound-social > a {
		display: inline-block;
		height: 40px;
		line-height: 40px;
		width: 40px;
		font-size: 14px;
		color: <?= $primary ?>;
		border: 1px solid #efefef;
		border-radius: 50%;
		margin: 3px;
		-webkit-transition: 0.2s all;
		transition: 0.2s all;
	}

	.notfound-social > a:hover {
		color: #fff;
		background-color: <?= $primary ?>;
		border-color: <?= $primary ?>;
	}

	@media only screen and (max-width: 480px) {
		.notfound .notfound-404 {
			position: relative;
			height: 168px;
		}

		.notfound .notfound-404 h1 {
			font-size: 100px;
		}

		.notfound h2 {
			font-size: 22px;
		}
	}
</style>
